on:
  workflow_call:
  name: Hello

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - run: npm install @octokit/action

        - uses: actions/hello-world-docker-action@v1
          with:
            who-to-greet: 'Mona the Octocat - TEMPLATE'
